USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 " \
             "Safari/537.36 "
ENDPOINT = "https://www.portaleargo.it/appfamiglia/api/rest/"
ARGO_CLIENT_VERSION = "1.9.3"

DASHBOARD_OPTIONS = {
    'ABILITA_AUTOCERTIFICAZIONE_FAM': False,
    'ALILITA_BSMART_FAMIGLIA': False,
    'ARGOMENTI_LEZIONE': True,
    'ASSENZE_PER_DATA': True,
    'COMPITI_ASSEGNATI': True,
    'CONSIGLIO_DI_CLASSE': True,
    'CONSIGLIO_DI_ISTITUTO': False,
    'DISABILITA_ACCESSO_FAMIGLIA': True,
    'DOCENTI_CLASSE': True,
    'GIUDIZI': False,
    'GIUSTIFICAZIONI_ASSENZE': True,
    'IGNORA_OPZIONE_VOTI_DOCENTI': True,
    'MODIFICA_RECAPITI': True,
    'NASCONDI_DIDUP_FAMIGLIA': True,
    'NOTE_DISCIPLINARI': True,
    'ORARIO_SCOLASTICO': True,
    'PAGELLE_ONLINE': True,
    'PAGELLINO_ONLINE': False,
    'PIN_VOTI': False,
    'PRENOTAZIONE_ALUNNI': True,
    'PROMEMORIA_CLASSE': True,
    'RECUPERO_DEBITO_INT': False,
    'RECUPERO_DEBITO_SF': False,
    'RENDI_VISIBILE_CURRICULUM': True,
    'RICHIESTA_CERTIFICATI': False,
    'TABELLONE_PERIODI_INTERMEDI': False,
    'TABELLONE_SCRUTINIO_FINALE': False,
    'TASSE_SCOLASTICHE': True,
    'VALUTAZIONI_GIORNALIERE': True,
    'VALUTAZIONI_PERIODICHE': True,
    'VALUTAZIONI_SOSPESE_PERIODICHE': False,
    'VOTI_GIUDIZI': True
}
